import { combineReducers } from 'redux';
import { reducer as formReducer } from 'redux-form';
import loginReducer from './loginReducer';
import socketReducer from './socketReducer';
import registerReducer from './registerReducer';
import * as storeTypes from '../constants/store/store-types';
import LogoutActions from '../constants/action-types/login';

const rootReducer = combineReducers({
  [storeTypes.LOGIN]: loginReducer,
  [storeTypes.FORM]: formReducer,
  [storeTypes.SOCKET]: socketReducer,
  [storeTypes.REGISTER]: registerReducer,
});

export default (state, action) => {
  if (action.type === LogoutActions.UNAUTH_USER) {
    // eslint-disable-next-line
    state = undefined;
  }
  // Delegate handling the action to the reducer generated by `combineReducers()`
  return rootReducer(state, action);
};